### ISSUE TITLE
[ExOpts Issue] Vinyl Menu crashes game when selecting a paintable vinyl (Debug Vinyls Option)

### ISSUE THREAD

**Issue by trackmaniamatt** [nlgzrgn/NFSMWExOpts#1]
When I try to select any other vinyl other than Contest Winners, and Unique 
vinyls with the Debug vinyls option on, for example, a body vinyl, the game crashes on me. It happens at 0x7c0aea, EDI register comes here as FFFFFFFF. It can't write into address [edi+0x11], which is 0x10 at this situation.

**Comment by y0urh34d** [comment]
I have the exact same issue, when I enable the special vinyl category, i select a vinyl that isnt unique, contest winners and the special vinyl, my game crashes

**Comment by trackmaniamatt** [comment]
Categories working with Special Vinyls Category on: National Flag, Contest Winners, Unique and Special

**Comment by trackmaniamatt** [comment]
Categories that crash the game with Special Vinyls Category on: Flame, Tribal, Stripes, Race Flag, and Body

**Comment by trackmaniamatt** [comment]
Just thought I'd mention the exact categories that work and don't work with the special vinyls on.

**Comment by nlgzrgn** [comment]
Sorry for this bug. I'll try to fix it with the next update. :)

**Comment by nlgzrgn** [comment]
I've fixed the bug with new build. (Build 4; Rev.04)
If you're an expert, you can download and compile the code yourself.
If you're not, you can wait until I make a new release.
Issue will be closed.
