### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by Futurehawk9896** [nlgzrgn/NFSMWExOpts#11]
I have no idea how to use visual studio and the instructions are not very clear. coan you please reply of make a video showing how to compile. 
Thanks

**Comment by osdeverr** [comment]
welp download a precompiled version lol

**Comment by nlgzrgn** [comment]
Compile instructions are added into [ExOpts Wiki](https://github.com/nlgzrgn/NFSMWExOpts/wiki/Getting-Started).
