### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by N3on9999** [nlgzrgn/NFSMWExOpts#15]
NOT WORKİNG FOR ME

ANYONE HELP ME PLS

**Comment by DiamondMaster07** [comment]
Official ExOpts tutorial:
https://youtu.be/G6Gd0dLsU3o

**Comment by N3on9999** [comment]
dude its not working

**Comment by DiamondMaster07** [comment]
Do you have all the requirements? 
Latest patch, required .exe, Visual C++ Runtimes?
Also what's the problem exactly? Does it give an error message or something?

**Comment by N3on9999** [comment]
i have all needed things but the lastest version (build 6) is not working

**Comment by DiamondMaster07** [comment]
Do you have an error message?

**Comment by N3on9999** [comment]
no i dont see the copyright text
i bet my pc did not guess it

**Comment by DiamondMaster07** [comment]
Can you record a video or take a screenshot?

**Comment by N3on9999** [comment]
ok i will upload it later

**Comment by N3on9999** [comment]
There You Go
​

2017-06-29 15:00 GMT+03:00 DiamondMaster07 <notifications@github.com>:

**Comment by DiamondMaster07** [comment]
Well I can't see any of the screenshots. Upload them to GitHub directly, pls, thx.

**Comment by N3on9999** [comment]
![speed 2017-06-30 12-09-10-836](https://user-images.githubusercontent.com/29772149/27744695-32b1c4a6-5dc9-11e7-9fbf-8994e8576008.jpg)
 
Here

**Comment by N3on9999** [comment]
there is no text like this 

Extra Options by ExOpts Team

**Comment by DiamondMaster07** [comment]
Possible problems: 1. Either you disabled the copyright takeover
2. ModLoader deletes that text

**Comment by N3on9999** [comment]
1: no i dont disabled it 
2: do i need to delete modloader?

**Comment by DiamondMaster07** [comment]
You don't need to delete modloader, you can easily disable it in it's config file

**Comment by N3on9999** [comment]
disabling text will be work? if so i will be hyped

**Comment by DiamondMaster07** [comment]
You can't just disable the modloader text. You need to disable modloader completely but ExOpts works either it's text appears or not

**Comment by N3on9999** [comment]
so? what do i should do?
