### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Rbn3D** [nlgzrgn/NFSMWExOpts#6]
Hi, i'm trying to install NFSMWExOps with no luck.

My installation has 1.3 exe and works fine, however it doesn't have a scripts folder by default, and even creating that folder and following installation steps, the game works, but nothing is injected. 

Also tried to rename the .asi file to d3d9.dll and copying it to the main folder, but the game crashes.

Any advice to make it work?

**Comment by nlgzrgn** [comment]
Hi! You're doing it wrong. 😛 

**!** Don't rename or change anything. 
Just copy the **dinput8.dll** file and **scripts** folder from **Main Folder** into your **NFSMW Installation Directory.**
_(It's usually in: C:\Program Files (x86)\EA GAMES\Need for Speed­(TM) Most Wanted)_

![exoptshowto](https://cloud.githubusercontent.com/assets/1937572/19944965/05abda1e-a14f-11e6-873e-f07398488bbf.png)

**Comment by Rbn3D** [comment]
Ahhh ok thanks, now it's working! My issue was that I grabbed from source, there is no dinput8.dll

Thanks!

**Comment by nlgzrgn** [comment]
Thank you! That was my fault. I'll add a "Download Ultimate ASI Loader" link into the Read Me there. I'm closing the issue.
