### ISSUE TITLE
[GitHub] Add compiled release

### ISSUE THREAD

**Issue by Keith94** [nlgzrgn/NFSMWExOpts#8]
Hi!

Can you add a compiled version to the [releases page](https://github.com/nlgzrgn/NFSMWExOpts/releases)? Similar to your Carbon repo. Thanks.

**Comment by nlgzrgn** [comment]
That was something I was planning to do. Thank you for reminding that to me. I think I'll do it in a week.

**Comment by nlgzrgn** [comment]
Added all Extra Options releases into their repos' releases pages.

Sorry for late comment.
