### ISSUE TITLE
[Enhancement] Widescreen Splash

### ISSUE THREAD

**Issue by Aero52** [nlgzrgn/NFSMWExOpts#9]
The proper way to enable widescreen splash? This also repositions the NFSMW logo, repositions the police lights, removes the patch number, and changes the text to "Please press START to begin". 

![Splash](http://i.imgur.com/mNjEIgl.gif)

```
// allows widescreen splash texture to load
005A3080 nop
005A3081 nop

// pointers are changed to "WS_MW_LS_Splash.fng" string
008F3C68 0089F828
008F3C88 0089F828
008F3CA4 0089F828
```

**Comment by nlgzrgn** [comment]
Nice! Thanks for the improvement.

But I think this fits to Widescreen Fix better. (You did something for the splash on NFSC, and it comes with WS fix)
If 13AG adds this to his NFSMW fix, I can ditch the option for it ([Menu]WideSplashScreen ) from Extra Options.

**Comment by Aero52** [comment]
The truth is I treat the widescreen fix as a "remaster" patch that includes improvements and features that should have been in the PC version, but I wasn't too sure about this one due to the other changes it makes.

Anyway, I've asked ThirteenAG and he said he'll do it. I'll go ahead and close this.
